-- AlterTable
ALTER TABLE `HistoricalPrice` ADD COLUMN `discount` DECIMAL(65, 30) NOT NULL DEFAULT 0,
    ADD COLUMN `originalPrice` DECIMAL(65, 30) NOT NULL DEFAULT 0,
    MODIFY `price` DECIMAL(65, 30) NOT NULL DEFAULT 0;
